### ISSUE TITLE
Cannot find libclang error

### ISSUE THREAD

**Issue by HonestDeng** [ICL-ml4csec/VulBERTa#1]
When running the fifth code block in Evaluation_VulBERTa-MLP.ipynb, an error occured:
_LibclangError: [WinError 126] 找不到指定的模块。. To provide a path to libclang use Config.set_library_path() or Config.set_library_file()._
And then I find that _"cidx = cindex.Index.create()"_ in class _Mytokenizer_ is responsible for this error. Looks like clang cannot find libcland.dll. 
Someone can help me? Thanks

**Comment by hazimfrodo** [comment]
The error might stem from a missing **libclang** library.
The easiest way to solve the libclang dependency problem is to install the `libclang` package instead of `clang`.
Because `clang` requires you to manually install Clang LLVM compiler into your system, whereas `libclang` will provide you the library.
So, try:  
`pip install libclang`

**Comment by HonestDeng** [comment]
@hazimhanif 
Thanks! I had solved this problem by installing _Clang LLVM_ compiler into my Windows system, but there were some troubles when I tried to install _Clang LLVM_ compiler into my Ubuntu. 
Two hours ago I tried to install _libclang_ and solved this problem in Ubuntu.
Thanks again!
